spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testesdb
    username: postgres
    password: 7992
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: testessch
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

  logging:
    pattern:
      console: "%d %-5level %logger : %msg%n"
    level:
      org.hibernate: debug
  #  sql:
  #    init:
  #      mode: always
  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.yaml
    default-schema: testessch


