spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/testdb
    username: root
    password: pass
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: off
    properties:
      hibernate:
#        format_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

  logging:
    pattern:
      console: "%d %-5level %logger : %msg%n"
    level:
      org.hibernate: debug
  #  sql:
  #    init:
  #      mode: always
#  liquibase:
#    enabled: true
#    change-log: classpath:db.changelog/db.changelog-master.yaml
#    default-schema: testessch

